x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - spark-data:/bitnami
    - ./sources/apps:/opt/spark-apps
    - ./sources/data:/opt/spark-data
    - ../shared:/shared
  networks:
    - common-network

services:
  spark-master:
    <<: *spark-common
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_USER=spark
    ports:
      - "8081:8081"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master

networks:
  common-network:
    name: common-network

volumes:
  spark-data:
