services:
  spark-master:
    build: .
    image: spark-cluster
    hostname: spark
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./sources/data:/opt/spark/data
      - ./sources/apps:/opt/spark/apps
      - ./sources/logs:/opt/spark/spark-events
    env_file:
      - .env
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - common-network


  spark-history-server:
    build: .
    image: spark-cluster
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env
    volumes:
      - ./sources/logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - common-network

  spark-worker:
    build: .
    image: spark-cluster
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env
    volumes:
      - ./sources/data:/opt/spark/data
      - ./sources/apps:/opt/spark/apps
      - ./sources/logs:/opt/spark/spark-events
    networks:
      - common-network


networks:
  common-network:
